version: "3"

services:
  # gui-react:
  #   container_name: timetable-gui-react
  #   build:
  #     context: ./gui-react
  #     dockerfile: gui-react.Dockerfile
  #   depends_on:
  #     - api
  #   environment:
  #     REACT_APP_API_URL: http://localhost:3000/api
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./gui-react:/usr/src/app
  #     - /usr/src/app/node_modules

  gui-vue3:
    container_name: timetable-gui-vue
    build:
      context: ./gui-vue3
      dockerfile: gui-vue3.Dockerfile
    depends_on:
      - api
    environment:
      # VUE_APP_API_URL: http://localhost:3000/api
      VITE_API_URL: http://localhost:3000/api
      VITE_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./gui-vue3:/usr/src/app
      - /usr/src/app/node_modules

  api:
    container_name: timetable-api
    build:
      context: ./api
      dockerfile: api.Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://timetable:password@database:5432/timetable
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

  database:
    container_name: timetable-db
    build:
      context: ./db
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - database.env
    volumes:
      - timetable-data:/var/lib/postgresql/data

volumes:
  timetable-data:
    driver: local
